### ISSUE TITLE
hipSYCL support

### ISSUE THREAD

**Issue by illuhad** [codeplaysoftware/oneapi-construction-kit#123]
### Version

latest

### What is your question or problem?

As part of the ongoing collaboration between Codeplay and Heidelberg University within the SYCLops project, we are committed to supporting targeting the construction kit with hipSYCL. The end goal here is to be able to support RISC-V hardware.

Since at least basic hipSYCL programs (have not yet tried more complex cases) now work with the construction kit after resolving issue #109, I am interested in your thoughts on what the next steps should be.

From your perspective, what are the requirements to advertising support for hipSYCL in addition to DPC++?
- Are there some particular validation requirements from your side?
- At which point and in what form do you think does it make sense to expand the readme with a hipSYCL section?
- Do you have any validation recommendations in general?

Obviously we would be working with you to address any issue that hipSYCL users might be reporting.

**Comment by coldav** [comment]
I'd be happy for you to add to the README at any point - it is open source and we welcome pull requests. Most of our testing remains OpenCL based which gives a good coverage of the backends. I will be restructuring and extending the documentation as some point.

We are currently running SYCL CTS and Intel's llvm test suite but don't have 100% pass rate on them yet.
We plan to add some testing on port-blas/dnn and some small examples including use of SYCLomatic. I can also look at adding in HipSYCL into our testing and we can report any issues we see.

I think it may be beneficial to discuss directly.

**Comment by illuhad** [comment]
> If you want to make a pull request to show how to use HipSYCL with OCK that would be great.

Great, I'll do this.

In the meantime I think we can close this issue.
