### ISSUE TITLE
Potential issues in the HAL/ComputeMux tutorials in the docs

### ISSUE THREAD

**Issue by manuelmohr** [codeplaysoftware/oneapi-construction-kit#150]
### Version

3.0.0

### What behaviour are you expecting?

This is a collection of potential issues I found after working through the two tutorials in the docs.  Thanks for preparing these tutorials!

(I'm raising a bug instead of a question/enhancement as this may result in a PR to fix some of the issues.  I'm also just creating one issue as everything is related to the two tutorials and I feel like otherwise the reports are too fine-grained.  Feel free to relabel or split the report if you prefer otherwise.)

### What actual behaviour are you seeing?

I observed the following (potential) issues in the tutorials:
1. Type mismatches/inconsistencies [in HAL step 5 (simple kernel scheduling)](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/doc/overview/tutorials/creating-new-hal/running-kernels/simple-kernel-scheduling.rst):
    The functions `populateSchedulingInfo()` and `allocateKUB()` are both declared as taking a parameter of type `wg_info_t&`, but are then called using an argument of type `exec_info_t` in the example code for `kernel_exec()`.  The type definition of `wg_info_t` shown in the tutorial includes no mention of an attribute `exec`, but `populateSchedulingInfo()` immediately grabs `wg.exec`.  The definition of `allocateKUB()` suddenly uses `exec_state_t&` as the type, which conflicts with the declaration immediately above.
    Moreover, the shown code for `populateSchedulingInfo()` references various fields that don't exist in the types defined in `device_if.h`, like `exec_state_t::local_size`, `exec_state_t::num_groups`, etc.
    This part was quite confusing to me.  I found that [the `.patch files`](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/doc/overview/tutorials/creating-new-hal/patches/tutorial1_step5_sub3.patch) that seem to mirror the HAL steps were internally consistent and contain working code, which I used in the end to continue with the tutorial.
    The markdown files contain inconsistent copies of these code snippets and I wondered whether there was maybe some refactoring in the past that accidentally didn't (fully?) update the code snippets in the markdown files.  I also wondered whether there's a smart way to ensure consistency between patch files and markdown docs (as it seems the patch files can be easily checked using the `setup_new_target_tutorial.sh` script).
1. Potential kernel interface inconsistency in ComputeMux tutorial:
    In the HAL tutorial, [the kernel interface is given as](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/doc/overview/tutorials/creating-new-hal/running-kernels/simple-kernel-scheduling.rst): `void kernel_main(uint64_t instance_id, uint64_t slice_id, const kernel_args *args, wg_info_t *wg)`.  This also matches the indices that the ComputeMux tutorial defines.  However, in the very last LLVM dump [here](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/doc/overview/tutorials/creating-a-new-mux-target/adapting-target-pass-pipeline.rst), it shows the interface as `@add(ptr %0, ptr %1, i64 %2, i64 %3)`, which seems to have the arguments and work-group pointers _first_ and _then_ the indices.  Maybe this was changed at some point but this part of the docs wasn't updated?
1. Potential memory leak in HAL step 3:
    In [step 3 of the HAL tutorial](https://github.com/codeplaysoftware/oneapi-construction-kit/tree/main/doc/overview/tutorials/creating-new-hal/hal-operations-step-03-loading-programs.rst) ("Loading programs on the device"), the sample code for `program_find_kernel()` creates a new object of type `refsi_hal_kernel` but I think it never gets deleted.  I noticed that the [reference implementation](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/main/examples/refsi/hal_refsi/include/refsi_hal.h#L49) contains a bit more code to manage ownership correctly, so if this is an intentional leak to simplify the example code, feel free to ignore this point.
1. Potentially unnecessary padding in `alignBuffer()` function in HAL step 5:
    I think the [`alignBuffer()` function](https://github.com/codeplaysoftware/oneapi-construction-kit/blob/fcd8a60e13ec6a5734afa8589d12fe88d157dd88/examples/refsi/hal_refsi/source/refsi_hal_m1.cpp#L301) unnecessarily inserts `align` bytes of padding if the buffer size is already aligned to `align` bytes.  This is not inherently harmful, but can be confusing when trying to unpack the buffer based on one's mental model gained from reading the packing code (as I didn't expect `alignBuffer(buf, 8)` to do anything to a buffer of size `8`).  Can be fixed, e.g., by directly returning from `alignBuffer()` if the buffer size is already aligned.

### What steps are required to reproduce the bug?

Follow the tutorial and potentially get stuck, confused, or at least left wondering :)

**Comment by manuelmohr** [comment]
One addition after your question in the call about `create_target.py`: I think the problem I encountered is that I used a relative path for `--external-dir`, which apparently doesn't work.

If you run the script exactly as given in the docs, everything works, so it's a very minor issue.

```
/tmp$ mkdir test
/tmp$ /tmp/oneapi-construction-kit/scripts/create_target.py /tmp/oneapi-construction-kit/ /tmp/oneapi-construction-kit/scripts/new_target_templates/refsi.json --external-dir /tmp/test/ # Works
/tmp$ mkdir test2
/tmp$ /tmp/oneapi-construction-kit/scripts/create_target.py /tmp/oneapi-construction-kit/ /tmp/oneapi-construction-kit/scripts/new_target_templates/refsi.json --external-dir test2/
Traceback (most recent call last):
  File "/tmp/tmpvoswfb0r.py", line 91, in <module>
    os.remove(os.path.join(dst_test_dir, "refsi_tutorial_wrapper_pass.ll"))
FileNotFoundError: [Errno 2] No such file or directory: 'test2/compiler/refsi_tutorial/test/refsi_tutorial_wrapper_pass.ll'
Stopping generation because post_gen_project hook script didn't exit successfully
Hook script failed (exit status: 1)
```

**Comment by frasercrmck** [comment]
Hi @manuelmohr, sorry for the delay and thank you again for the feedback!

I opened #248 which hopefully fixes all of the issues you raised.

**Comment by frasercrmck** [comment]
I'm going to close this issue now. If you find any more issues in our tutorials or docs, we can open another separate ticket (or alternatively re-open this one if I didn't correctly resolve the issues you've reported).
