### ISSUE TITLE
Out-of-order queue support not reported

### ISSUE THREAD

**Issue by EwanC** [codeplaysoftware/oneapi-construction-kit#422]
### Version

git commit b7afa18deabf90c06e018e07c0240433bfe4ab1b

### What behaviour are you expecting?

It looks like the `CA_ENABLE_OUT_OF_ORDER_EXEC_MODE` CMake variable which is set to ON by default enables `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` to be set on queue creation. 
However, neither `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE`  from `CL_DEVICE_QUEUE_PROPERTIES` or `CL_COMMAND_BUFFER_CAPABILITY_OUT_OF_ORDER_KHR` from `CL_DEVICE_COMMAND_BUFFER_CAPABILITIES_KHR` are being returned from the appropriate queries to report device support. I would expect this to be the case for a conformant OpenCL implementation that supports out-of-order queues.

I'd also expect `clCreateCommandQueueWithProperties` & `clCreateCommandQueue` to return the following specific returned code when `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` is asked for but the device doesn't report support. However, the device currently accepts the queue property, which is confusing.
> [CL_INVALID_QUEUE_PROPERTIES](https://registry.khronos.org/OpenCL/specs/3.0-unified/html/OpenCL_API.html#CL_INVALID_QUEUE_PROPERTIES) if values specified in properties are valid but are not supported by the device.

### What actual behaviour are you seeing?

Neither `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE`  from `CL_DEVICE_QUEUE_PROPERTIES` or `CL_COMMAND_BUFFER_CAPABILITY_OUT_OF_ORDER_KHR` from `CL_DEVICE_COMMAND_BUFFER_CAPABILITIES_KHR` are being returned from the appropriate device queries but `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` is accepted as a property on command-queue creation.

### What steps are required to reproduce the bug?

`./bin/UnitCL --opencl_info`  Shows `CL_DEVICE_QUEUE_PROPERTIES : CL_QUEUE_PROFILING_ENABLE` when the outcome of that query should have `CL_QUEUE_OUT_OF_ORDER_EXEC_MODE_ENABLE` in it.

### Anything else we should know?

Should consider setting `CA_ENABLE_OUT_OF_ORDER_EXEC_MODE` to OFF by default until its behaviour can be conformant.

**Comment by EwanC** [comment]
> We are currently passing OpenCL CTS. Is this a conformance issue that is not covered by the CTS? If so, we may also want to raise a ticket there.

You're right this should be in the CTS, I've opened a PR to add this coverage https://github.com/KhronosGroup/OpenCL-CTS/pull/1935

**Comment by hvdijk** [comment]
Fixed by https://github.com/codeplaysoftware/oneapi-construction-kit/pull/425, thanks, and have confirmed that this passes CTS with your PR applied.

**Comment by EwanC** [comment]
Thanks 👍
