### ISSUE TITLE
OpenCL for device environment

### ISSUE THREAD

**Issue by ShivaChen** [codeplaysoftware/oneapi-construction-kit#473]
### Version

2.0.0

### What is your question or problem?

Hi,

I was trying to use x86 as host and riscv as device with oneapi-construction-kit. To my understanding SYCL is based on OpenCL.
My question is does the device environment would be required to install OpenCL library such as POCL?
Or the OpenCL semantic can be handled by host and not need OpenCL library on device?

**Comment by coldav** [comment]
Hi,
Sorry about the delay.

I assume you mean that you want to run some SYCL on an x86 host which connects to a risc-v device 

The oneapi-construction-kit will create an OpenCL library, this can be used as a plugin by dpc++ to build and run SYCL. There should be some instructions in the README and elsewhere in the documentation to clarify this.
POCL can potentially be used in a similar way as a plugin, but you'd need to look at the pocl documentation for that.

**Comment by coldav** [comment]
@ShivaChen Is this helpful? Would you be happy if I close the issue now?

**Comment by ShivaChen** [comment]
Yes, thanks for your kind reply.

**Comment by coldav** [comment]
no problem.
