### ISSUE TITLE
-cl-uniform-work-group-size causes error -43

### ISSUE THREAD

**Issue by illuhad** [codeplaysoftware/oneapi-construction-kit#476]
### Version

4.0

### What behaviour are you expecting?

Compiling a kernel with `-cl-uniform-work-group-size` should succeed.

### What actual behaviour are you seeing?

Compiling the program returns error -43 (`CL_INVALID_BUILD_OPTIONS`)

### What steps are required to reproduce the bug?

Probably submit any SPIR-V with `-cl-unform-work-group-size`, I encountered the issue when testing the OCK with current AdaptiveCpp, which uses this build option. Removing the `-cl-uniform-work-group-size` flag allows the program to compile and run correctly.

**Comment by coldav** [comment]
Thanks I can confirm we also see this, we'll look into this.

**Comment by coldav** [comment]
I'll close this, let us know if you have any further problems.
