### ISSUE TITLE
Update to latest upstream headers

### ISSUE THREAD

**Issue by EwanC** [codeplaysoftware/oneapi-construction-kit#479]
### Brief overview

OCK uses a copy of the https://github.com/KhronosGroup/OpenCL-Headers/ in `source/cl/external/OpenCL-Headers`. This copy has become out of date such that using tip OpenCL-Headers causes OCK to fail to build with error:
```
/home/ewan/Development/Codeplay/oneapi-construction-kit/source/cl/test/UnitCL/source/Common.cpp:781:12: error: ‘CL_DEPTH_STENCIL’ was not declared in this scope
  781 |       CASE(CL_DEPTH_STENCIL);
      |            ^~~~~~~~~~~~~~~~
/home/ewan/Development/Codeplay/oneapi-construction-kit/source/cl/test/UnitCL/source/Common.cpp:762:8: note: in definition of macro ‘CASE’
  762 |   case VALUE:       \
      |        ^~~~~
/home/ewan/Development/Codeplay/oneapi-construction-kit/source/cl/test/UnitCL/source/Common.cpp: In lambda function:
/home/ewan/Development/Codeplay/oneapi-construction-kit/source/cl/test/UnitCL/source/Common.cpp:804:12: error: ‘CL_UNORM_INT24’ was not declared in this scope; did you mean ‘CL_UNORM_INT8’?
  804 |       CASE(CL_UNORM_INT24);
      |            ^~~~~~~~~~~~~~
/home/ewan/Development/Codeplay/oneapi-construction-kit/source/cl/test/UnitCL/source/Common.cpp:762:8: note: in definition of macro ‘CASE’
  762 |   case VALUE:       \
      |        ^~~~~
[91/311] Building CXX object source/cl/test/UnitCL/CMakeFiles/UnitCL.dir/source/KernelArgumentTypes.cpp.o
ninja: build stopped: subcommand failed.
```

That is with `-DCL_TARGET_OPENCL_VERSION=300`

### What behaviour are you expecting?

I'd like to see OCK update it's headers to tip OpenCL-Headers and successfully build.

### What current behaviour are you seeing?

OCK fail to build when tip upstream headers are used.

### Anything else we should know?

Having the most recent headers helps being able to use OCK to prototype spec changes that involve updating the OpenCL headers, as the diff with OpenCL-Headers is smaller. e.g https://github.com/EwanC/oneapi-construction-kit/pull/1

**Comment by hvdijk** [comment]
Updated to the latest tag in https://github.com/codeplaysoftware/oneapi-construction-kit/pull/490, we also switched to FetchContent which hopefully makes it easier to quickly test a different version, it just needs a one line update.
